project:
  type: website
  output-dir: docs
  
website:
  title: "Georgios Manalis"
  navbar:
    right:
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: policywork.qmd
        text: Policy work

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

