---
title: "Policy work"
---

As a research fellow the Hellenic Foundation for European and Foreign Policy (ELIAMEP), I worked closely with Manos Matsaganis (Head of the Greek and European economy observatory) to produce policy research focusing on the Greek economy. Our joint and my individual work can be found below:

## Short policy bulletins and media presence

### [In-Focus]{style="color: #A0522D;"}

weekly policy bulletins (with M. Matsaganis) published at ELIAMEP's website (in English) as well as in [Oikonomikos Tachydromos](https://www.ot.gr/?s=%CE%93%CE%B9%CF%8E%CF%81%CE%B3%CE%BF%CF%82+%CE%9C%CE%B1%CE%BD%CE%AC%CE%BB%CE%B7%CF%82) (in Greek)

### [Bi-weekly articles]{style="color: #A0522D;"}

published at [capital.gr](https://www.capital.gr/search/?query=Γιώργος%20Μανάλης&sort=daterelevance) (in Greek)

## Policy papers

### [Using RRF resources to kick-start a job-rich recovery in Greece]{style="color: #A0522D;"}

Policy paper #111/2022 (with M. Matsaganis) ELIAMEP's working paper series ([link](https://www.eliamep.gr/wp-content/uploads/2022/10/Policy-paper-111-Matsaganis-Manalis-EN-final.pdf)).

### [Promoting a just digital transition for workers]{style="color: #A0522D;"}

Policy study (with M. Matsaganis and [A. Zavarella](https://feps-europe.eu/person/avilia-zavarella/)) ([link](https://feps-europe.eu/publication/digital-transition-and-employment/)).

Part of the [Recovery Watch](https://feps-europe.eu/theme/recovery-watch/) series of publications led by FEPS, Friedrich-Ebert-Stiftung (FES) and the Institut Emile Vandervelde (IEV), in collaboration with several first-rate research organisations.

### [National Recovery and Resilience Plan: Greece]{style="color: #A0522D;"}

(with M. Matsaganis) Italian Labour Law e-Journal Vol. 15, no. 1S (2022) ([link](https://illej.unibo.it/article/view/15650/14856)).
