---
title: "Research"
format: 
   html:
     include-in-header: 
        text: |
          <style>
          h3 {
          color: #A0522D;
          }
          </style>
---

## Working papers

### The Mystery of Land Rights: Explorations on Informal Institutions in Ghana

(with [K. Mazur](https://sites.google.com/site/mazurecon/home))

\[[Link to working paper](https://drive.google.com/file/d/1AKQbuWAvM1hBsS6STqLIpKXYt7fiKtA-/view?usp=sharing)\] - in preparation for the Carnegie-Rochester-NYU Conference Series on Public Policy - preliminary, comments welcome)

(previously circulated as 'Mutual insurance and land security in rural Ghana')

We investigate why informal institutions persist despite policy efforts to introduce formal alternatives. Using Ghana's nationwide rollout of land registration offices, we show that increased access to formal land institutions does not significantly raise land rights adoption. Instead, we show that local traditional authorities—village chiefs—actively constrain the formalization of agricultural land markets. We develop a structural model of endogenous take-up of land rights, integrating their effects on land markets and informal risk-sharing. While the estimated welfare cost of chiefs' power inhibiting the take-up of land rights is large, the model also reveals a critical trade-off: although enhanced formal land rights typically improve insurance and reduce misallocation, excessive formalization risks collapsing informal insurance networks. Thus, rural communities may rationally retain informal institutions to preserve their immediate benefits.

**Presented**: Departmental seminar - University of Cyprus (2020); STEG - CEPR annual conference (2021); Departmental seminar - University of Macedonia (2021); Asian Meeting of the Econometric Society in China (2022); SIOE - Toronto (2022); EEA - ESEM, Milan (2022); RES - SES, Glasgow (2023); AFES, Nairobi (2023); SED, Cartagena (2023); AFES, Abidjan (2024).

### Land rights and risk-sharing in rural West Africa

(revised draft coming soon)

Despite arduous efforts of advancing land rights in Africa, most of the continent experiences low levels of ownership security. Land reforms introduced by the state have failed to deliver the desired results of officially recognized property. I propose a novel contextualization of land rights that motivates a theoretical model to account for land reforms’ effects when implemented in weak institutional environments with high risk. In environments such as rural Africa, communities have developed informal mechanisms of risk-sharing to provide households with a safety net. Therefore, when a land reform, aiming at granting individual property rights, takes place, it operates in a highly antagonistic way to the established informal insurance mechanisms. I use survey data from a land reform initiated in Burkina Faso in 2009 to evince the interaction between land holdings and transfers among community members. Subsequently, I build a model of risk-sharing with limited commitment to explain the competing forces developed between statutory land reforms and customary risk-sharing networks at a community level. The model shows that a land reform increases the share of surplus that a villager can extract from a risk-sharing contract among community members and decreases the size of the pie available to the community. Additionally, it shows a non-monotonic relation between land allocation and productivity pointing towards a trade-off between output efficiency and size of risk-sharing. It accurately accounts for the low participation rates from rural population to the Burkina Faso land reform and it provides a reasoning for potential land misallocation.

**Presented**: Giorgio Rota Conference 2019 (University of Turin); Belgrade Young Economists Conference (BYEC 2019); Warsaw International Economic Meeting (WIEM 2019); ASSET 2019 Conference; IEWG (EUI); EERN 2020 Conference (University of Orléans); GLAD 2020 Conference (University of Göttingen); Conference on Research on Economic Theory and Econometrics - CRETE 2021.

**Awarded**: 7th Giorgio Rota Best Paper Award; Best paper at Warsaw International Economic Meeting 2019; Shortlisted for LAGV Prize (ASSET 2019).

### Contagion as a dealmaker? The effect of financial spillovers on regional lending programs

(with A. I. Bonk and [A. Fotiou](https://sites.google.com/site/alexandrafotiou/home)) - \[IMF Working Papers, Vol 2022: Issue 133 \]

The recent European sovereign debt crisis highlighted the critical role of regional lending arrangements. For the first time, European mechanisms were called to design financing programs for member countries in trouble. This paper analyses how the risk of contagion, an essential characteristic of interlinked economies, shapes borrowing conditions. We focus on the role of spillovers as a channel of bargaining power that a country might have when asking for financial support from regional lending institutions. We build and present a new database that records both the dates on which official meetings took place, relevant statements were released and the timing of the announcements regarding loan disbursements. This database allows us to assess the defining role that announcements of future actions have in mitigating spillover costs. In addition, we study the design of lending arrangements within a recursive contract between a lender and a sovereign country. When accounting for spillover costs, arising from the borrower to the creditor, we find that it is in the lender’s best interest to back-load consumption by giving more weight to future transfers in order to reduce contagion cost. Subsequently, we test and validate our theoretical predictions by assessing the effect of spillovers on loan disbursements to program-countries and by juxtaposing lending conditions imposed by the IMF and the European mechanisms.

**Presented**: Conference on Research on Economic Theory and Econometrics - CRETE 2019.

## Work in progress

### Local trade and mutual insurance

Opening to trade may pose challenges for small, open economies with weak risk-insurance mechanisms. Trade liberalization often leads to specialization in the production structure, a key outcome of classical trade theory. This specialization exposes economies to external fluctuations, resulting in increased earnings volatility. Consequently, economies with incomplete insurance markets potentially experience reduced welfare. This issue is particularly prominent in the context of small rural village economies in the developing world due to two primary factors: (i) the absence of formal risk-insurance mechanisms and (ii) the inherent volatility of agricultural output. In response to these challenges, rural village economies have developed informal practices of mutual insurance, such as gift-giving and production sharing, to achieve a degree of consumption smoothing. This project aims to quantitatively assess the interaction between the allocative effects of opening to trade with the distributional effects of informal mutual insurance mechanisms for rural populations in low-income countries engaged in local trade.

**Presented**: SES, Glasgow (2024); AFES, Abidjan (2024).

## Publications

### Trust dynamics in electoral competition

(with [N. Glynia](https://sites.google.com/view/nektaria-glynia/home) and [D. Xefteris](https://sites.google.com/site/dxefteris/)) - Vol 179, October 2025, European Economic Review

\[[Link to journal article](https://www.sciencedirect.com/science/article/pii/S0014292125001758?dgcid=author)\], \[[Working paper version](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4794513)\], \[[Replication code](https://github.com/GManalis/Trust_Dynamics_in_Electoral_Competition.git)\]

We study the fragility of trust between voters and politicians, exploring the likelihood of trust recovery following disruptions. We identify a critical trust threshold: above it, the trust dynamics converge to a stable steady state marked by politicians’ moderate deception and voters’ tempered expectations; below it, trust gradually declines, giving way to deepening scepticism. These insights highlight that while stable levels of trust are feasible, they should not be taken for granted, contributing to the discussion on the underpinnings of recent trust crises across European democracies.

### Bandwagons in costly elections: the role of loss aversion

(with [A. Leontiou](https://sites.google.com/view/anastasialeontiou) and [D. Xefteris](https://sites.google.com/site/dxefteris/)) - Vol 209, May 2023, Journal of Economic Behavior & Organization

\[[Link to journal article](https://www.sciencedirect.com/science/article/pii/S016726812300077X?via%3Dihub)\], \[[Replication code](https://github.com/GManalis/Bandwagons_in_Costly_Elections.git)\]

The formal study of voluntary elections with costly participation predicts that the supporters of the underdog - i.e., of the candidate that is expected to lose - are less likely to abstain than the supporters of the expected winner (Palfrey and Rosenthal, 1985; Herrera et al., 2014). While some empirical/experimental studies identify this underdog effect (Levine and Palfrey, 2007), in others bandwagons emerge: the supporters of the expected winner are found to abstain less often than the supporters of the underdog (Agranov et al., 2018). We focus on large elections and follow Köszegi and Rabin (2006) by considering that voters experience gains and losses with respect to their expected equilibrium payoffs. When the election is sufficiently close (i.e., when the shares of the supporters of the two alternatives are not too asymmetric), we find that bandwagons emerge in every equilibrium. To our knowledge, this is the first formal study that explains bandwagons in large elections, by incorporating a commonly accepted behavioural model in an otherwise standard context of costly voting.

## 
