---
title: "Teaching"
---

-   **History of Economic Thought**

    -   2025/26
    -   Department of Economics - Athens University of Economics and Business
    -   Compulsory course for 3rd year undergraduate students
    -   Course organizer and instructor

-   **International Economics**

    -   2022/23, 2023/24, 2024/25
    -   School of Economics - University of Edinburgh
    -   Honours course for 3rd and 4th year undergraduate students
    -   Course organizer and instructor

-   **International Trade**

    -   2022/23, 2023/24, 2024/25
    -   Scottish Graduate Programme in Economics - School of Economics - University of Edinburgh
    -   Course for MSc and PhD students
    -   Course organizer and instructor

-   **Advanced Topics in Macroeconomics**

    -   2024/25
    -   Scottish Graduate Programme in Economics - School of Economics - University of Edinburgh
    -   Course for MSc and PhD students
    -   Course organizer and instructor

-   **Topics in Microeconomics**

    -   2022/23, 2023/24
    -   School of Economics - University of Edinburgh
    -   Honours course for 3rd and 4th year undergraduate students
    -   Tutor
